name: Code Formatting Check

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP Code Sniffer
        run: |
          composer require --dev squizlabs/php_codesniffer=*
          composer require --dev drupal/coder
      - name: Check coding standards
        run: |
          vendor/bin/phpcs || true
      - name: Format Code
        run: |
          vendor/bin/phpcbf || true
      - name: Check if there are changes
        run: |
          if git diff --exit-code; then
            echo "No formatting changes needed";
          else
            echo "Formatting changes detected. Please commit the changes.";
            exit 1;
          fi
