name: Code Formatting Check

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP Code Sniffer
        run: |
          composer require --dev squizlabs/php_codesniffer=*
          composer require --dev drupal/coder
      - name: Check coding standards
        run: |
          vendor/bin/phpcs || true
      - name: Format Code
        run: vendor/bin/phpcbf
