name: Code Formatting Check

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP Code Sniffer
        run: |
          composer require --dev squizlabs/php_codesniffer=*
          composer require --dev drupal/coder
      - name: Check coding standards
        run: |
          vendor/bin/phpcs || true

      - name: Fix coding standards (PHP Code Beautifier and Fixer)
        run: |
          vendor/bin/phpcbf || true
      - name: Check if there are changes
        run: |
          # Verifica se há mudanças, excluindo os arquivos composer.json e composer.lock
          if git diff --name-only | grep -vE '^(composer\.json|composer\.lock)'; then
            echo "Formatting changes detected. Committing changes.";

            # Adiciona e comita as alterações
            git config --global user.email "github-actions@github.com"
            git config --global user.name "GitHub Actions"
            git add -A
            git commit -m "Fix code formatting"
            
            # Empurra as alterações para o branch
            git push
          else
            echo "No formatting changes needed";
          fi
